# Generated by Django 3.0.5 on 2020-04-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_piece_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='media_file',
            field=models.FileField(null=True, upload_to='issue_media/%Y/%m/'),
        ),
    ]
