# Generated by Django 3.0.5 on 2020-04-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200405_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='issue_media/%Y/%m/'),
        ),
    ]
