# Generated by Django 3.0.5 on 2020-04-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(verbose_name='date submitted')),
                ('author_name', models.CharField(max_length=200)),
                ('author_email', models.EmailField(max_length=254)),
                ('cover_letter', models.TextField()),
                ('submission_file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('editor_notes', models.TextField()),
                ('submission_status', models.CharField(choices=[(0, 'Recieved'), (1, 'Under Review'), (2, 'Accepted'), (3, 'Rejected')], default='Recieved', max_length=10)),
            ],
        ),
    ]
